version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./data:/var/www/html"
      - "./nginx/log:/var/log/nginx"
    environment:
      TZ: "Asia/Tokyo"
  log:
    build: ./fluentd
    environment:
      FLUENTD_CONF: "my_fluentd.conf"
      TZ: "Asia/Tokyo"
    volumes:
      - "./fluentd/fluentd.conf:/fluentd/etc/my_fluentd.conf"
      - "./fluentd/log:/fluentd/log"
      - "./nginx/log:/var/log/nginx"
  elasticsearch:
    image: elasticsearch:5
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./es_data/:/usr/share/elasticsearch/data/
  kibana:
    image: kibana:5
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

